---
- name: Create or Update Virtual Servers
  bigip_virtual_server:
    provider: "{{ provider }}"
    name: "{{ item.name }}"
    destination: "{{ item.destination }}"
    port: "{{ item.port }}"
    pool: "{{ item.pool }}"
    profiles: "{{ item.profiles | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ f5_virtual_servers }}"
  when: f5_virtual_servers is defined
